#version: '3.8'

services:

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: respawn_kafka
    container_name: respawn_kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft settings
      KAFKA_KRAFT_MODE: 'true'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@respawn_kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      # Those are the listeners that Kafka will advertise to clients, put those value in configuration placeholders
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://respawn_kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      
      # Persistence & Logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      # Required for KRaft to initialize storage automatically
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' 
    volumes:
      - kafka_data:/var/lib/kafka/data
      


  postgres:
    image: postgres:latest
    container_name: portgres_respawn
    environment:
      # These ${VARIABLES} are read from the .env file in the same directory as docker-compose.yml
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      # Format is: host_path : container_path
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql # Persist data on host machine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  grpc-server-springboot-service:
      build:
        context: . # starts from the directory of the docker-compose.yml file
        dockerfile: java_projects/ResPawn/Dockerfile
      container_name: respawn-grpc-server
      ports:
        - "8080:8080"
        - "6767:6767"

        # copy all application properties that use ${...} 
        # syntax to read from environment variables, as spring boot in the 
        # container won't have access to the .env file directly, 
        # but will read the .env variables passed in through docker-compose    
      environment:
        # --- Database (Matches application.properties placeholders) ---
        DB_URL: ${DOCKER_DB_URL}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DRIVER: org.postgresql.Driver
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_GRPC_SERVER_PORT: 6767

        # gRPC & Server SSL 
        IS_SSL_ENABLED: "true"
        KEYSTORE_LOCATION: ${RELATIVE_KEY_PATH}
        SSL_KEYSTORE_PATH: ${RELATIVE_KEY_PATH}
        KEYSTORE_PASSWORD: ${KEY_PASSWORD}
        SSL_KEYSTORE_PASSWORD: ${KEY_PASSWORD}
        KEY_PASSWORD: ${KEY_PASSWORD}
      
        # Kafka (Matches application.properties placeholders)
        # Pointing to the Kafka container's internal hostname and port, 
        # not localhost, since this is from the perspective of the Spring Boot container
        SPRING_KAFKA_BOOTSTRAP_SERVERS: respawn_kafka:29092
        # Consumer 
        SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: respawn_kafka:29092
        SPRING_KAFKA_CONSUMER_GROUP_ID: respawn-group
        SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
        SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
        SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
        SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: com.respawn
        # Producer
        SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: respawn_kafka:29092
        SPRING_KAFKA_PRODUCER_ACKS: -1
        SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
        SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer

      volumes:
        # Mapped ./self_signed_cert (host) to /app/self_signed_certs (container)
        - ./self_signed_certs:/app/self_signed_certs:ro
      depends_on:
        postgres:
          condition: service_healthy

    
  grpc-client-dotnet-services:
    build:
      context: .
      dockerfile: C_sharp/Dockerfile
    container_name: respawn-grpc-client
    ports:
      - "6760:6760"
    environment:
      # run in development mode to enable hot reload and other dev features
      ASPNETCORE_ENVIRONMENT: Development # remove it for production
      # Key and certificate properties for gRPC client TLS configuration + JWT properties for authentication
      PFX_FILE_PATH: ${PFX_FILE_PATH}
      PFX_PASSWORD: ${PFX_PASSWORD}
      JWT__KEY: ${JWT__KEY}
      JWT__ISSUER: ${JWT__ISSUER}
      JWT__AUDIENCE: ${JWT__AUDIENCE}
      JWT__SUBJECT: ${JWT__SUBJECT}
      
    volumes:
      # Mapped ./self_signed_cert (host) to /app/self_signed_certs (container)
      - ./self_signed_certs:/app/self_signed_certs:ro # :ro means read-only
    depends_on:
      grpc-server-springboot-service:
        condition: service_started

volumes: # Define named volumes for data persistence
  kafka_data:
    name: kafka_data
  db_data:
    name: db_data
  self_signed_certs:
    name: self_signed_certs