spring.application.name=ReSpawnMarket

# database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
# maybe we need this later
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# gRPC server
spring.grpc.server.enabled=true
spring.grpc.server.port=6767

# gRPC TLS/SSL configuration
# this has to be false for local testing with self-signed certs
spring.grpc.server.ssl.secure=true
spring.grpc.server.ssl.bundle=sep3
spring.ssl.bundle.jks.sep3.keystore.location=${KEYSTORE_LOCATION}
spring.ssl.bundle.jks.sep3.keystore.password=${KEYSTORE_PASSWORD}
spring.ssl.bundle.jks.sep3.keystore.type=PKCS12
spring.ssl.bundle.jks.sep3.key.password=${KEY_PASSWORD}

# kafka configuration (non env variables for now)
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=respawn-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=org.example.respawnmarket

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=-1
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Spring Boot server configuration
server.port=8080
server.ssl.enabled=${IS_SSL_ENABLED}
server.ssl.key-store=${SSL_KEYSTORE_PATH}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12

spring.security.user.name=sep3admin
spring.security.user.password=Pass1234