spring.application.name=ResPawn

# database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
# maybe we need this later
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# gRPC server (plaintext — TLS terminated by Caddy at the edge)
spring.grpc.server.enabled=true
spring.grpc.server.port=6767
spring.grpc.server.ssl.secure=false

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# Spring Boot server configuration
server.port=8080

spring.security.user.name=sep3admin
spring.security.user.password=Pass1234